#https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries
#https://kind.sigs.k8s.io/docs/user/ingress/
#extraPortMappings allow the local host to make requests to the Ingress controller over ports 80/443
#node-labels only allow the ingress controller to run on a specific node(s) matching the label selector
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP        
- role: worker
  extraPortMappings:
    - containerPort: 30010
      hostPort  : 30010
- role: worker
  extraPortMappings:
    - containerPort: 30020
      hostPort: 30020
